# Generated by Django 4.1.7 on 2023-03-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_first_name_teacher_last_name_teacher_user_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='teacher',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(default='1', unique=True),
        ),
    ]
