# Generated by Django 4.1.7 on 2023-03-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
