# Generated by Django 4.1.7 on 2023-03-25 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lecture_id',
            new_name='lecture',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('lecture_id', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('s_no', 'lecture')},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='teacher_id',
        ),
    ]
