# Generated by Django 4.1.7 on 2023-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_course_credit_hours_alter_course_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(default='3', max_length=1),
        ),
    ]
