# Generated by Django 4.1.7 on 2023-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_credit_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
