# Generated by Django 4.1.7 on 2023-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.SmallIntegerField(default=1),
        ),
    ]
