# Generated by Django 4.1.7 on 2023-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_question_unique_together_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(choices=[('3', '3'), ('4', '4')], max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='discipline',
            field=models.CharField(choices=[('BSCS', 'BSCS'), ('BSSE', 'BSSE'), ('BSAI', 'BSAI')], max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=5),
        ),
    ]
